#长期（3–7 天）：示例以 5m bar 为例，horizon_bars=234 即 1 周

data:
  
  # 数据源类型: csv | mysql | api
  source_type: mysql  # 改为 'csv' 使用CSV文件
  
  # CSV配置（当source_type=csv时使用）
  csv:
    input_csv: examples/rb0.csv
    timestamp_col: datetime
    ticker_col: ticker
    
  # MySQL配置（当source_type=mysql时使用）
  mysql:
    host: 192.168.0.204
    port: 3306
    user: root
    password:  # 建议使用环境变量
    database: akshare_data
    charset: utf8mb4
    table_name: raw_futures_zh_minute_sina
    
    # 查询参数
    query:
      tickers: [SP0,SR0,I0]  # 可以查询多个品种
      freqs: [5]
      start_date: "2025-08-01 00:00:00"
      end_date: "2026-10-25 23:59:59"


    # 列名映射（如果数据库列名不同）
    columns_mapping:
      trade_datetime: timestamp
      param_symbol: ticker
      param_period: freq
      open_price: open  # 如果列名相同则不需要映射
      high_price: high
      low_price: low
      close_price: close
      # volume: volume
  
  # API配置（当source_type=api时使用）
  api:
    adapter: akshare  # yfinance | alpha_vantage | finnhub | twelvedata | akshare
    symbols: [RB0]
    interval: 1min
    period: 30  # 天数
  
  # 通用配置
  ohlcv_cols: [open, high, low, close, volume]
  freq: 5min
  train_test_split_date: 2025-10-16 15:00:00 # 示例

features:
  rsi_periods: [14]
  macd: [12, 26, 9]
  sma_windows: [5, 10, 20, 60]
  ema_windows: [5, 10, 20, 60]
  vol_windows: [10, 20, 60]
  hold_windows: [5, 10, 20, 60]
  bb_window: 20
  bb_k: 2.0
  parkinson_window: 20
  cross_asset: [] # 可填外部品种close列路径或预处理结果

label:
  horizon_bars: 234 # ~1周（按5m）
  label_type: "binary" # binary|trinary|regression
  threshold: 0.0005 # 仅用于trinary或过滤

train:
  model_family: "ensemble" # lstm|transformer|xgboost|ensemble
  seed: 123
  batch_size: 256
  epochs: 20
  lr: 1e-3
  optimizer: adamw
  l2: 1e-4
  device: "cpu" #or cuda
  ddp: false
  num_workers: 4
  early_stop_patience: 20
  class_weight: 1.0
  valid_metric: "acc" # acc|f1|auc|rmse|mae
  out_dir: "out/swing"
  window: 64
  xgb_rounds: 1000
  xgb:
    num_rounds: 1000              # 目标轮次
    early_stopping_rounds: 1000     # 0 或省略 = 关闭早停；想保留就填 50/100 等
    internal_valid: false        # 关闭内部“末 20%”验证；用全局 split_date 划分
    valid_ratio: 0.2             # 仅在 internal_valid=true 时生效
    verbose_every: 100            # 日志打印频率；想每轮都看就设 1
  ensemble:
      mode: "stacking"
      beta: 0.7 #分类占70%， 回归占30%
      trials: 6000
inference:
  device: cpu
  preload: {}
  watchlist: [SP0,105.INTC]
  interval_seconds: 60
  window: 64 
backtest:
  side: "longshort" # longonly|longshort
  trans_cost_bp: 1.0 # 单边基点
  slippage_bp: 0.5
  threshold_prob: 0.55 # 入场阈值
  vol_target: 0.02 # 日化目标波动